import fs from 'fs/promises';
import { spawn } from 'child_process';
import chalk from 'chalk';

export async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

export function formatOutput(text) {
  return text
    .split('\n')
    .map(line => line.trim() ? `  ${line}` : '')
    .join('\n');
}

export async function commitToGit(filePath) {
  return new Promise((resolve, reject) => {
    const git = spawn('git', ['add', filePath], { stdio: 'pipe' });
    
    git.on('close', (code) => {
      if (code !== 0) {
        console.log(chalk.yellow('⚠️  Failed to add file to Git'));
        resolve();
        return;
      }
      
      const commit = spawn('git', ['commit', '-m', 'Add Claude profile generated by claude-profile-cli'], { stdio: 'pipe' });
      
      commit.on('close', (commitCode) => {
        if (commitCode === 0) {
          console.log(chalk.green('✅ Committed to Git'));
        } else {
          console.log(chalk.yellow('⚠️  Failed to commit to Git'));
        }
        resolve();
      });
      
      commit.on('error', () => {
        console.log(chalk.yellow('⚠️  Git not available'));
        resolve();
      });
    });
    
    git.on('error', () => {
      console.log(chalk.yellow('⚠️  Git not available'));
      resolve();
    });
  });
}